### PR TITLE
TS-4435: Enable compilation with openssl 1.1

### PR DESCRIPTION
**Pull request by shinrich**
Openssl 1.1 removes the locking and thread id callbacks.  It deduces system you are on and uses the appropriate threading interface.

Openssl 1.1 removes the ability to define objects on the stack, so we must create EVP digest objects.

Openssl 1.1 removes a number of client alert reason defines.

### CODE REVIEW

**Comment by atsci** [comment]
Linux (CentOS7) build finished successfully. Details on https://ci.trafficserver.apache.org/job/Github-Linux/21/

File: iocore/net/SSLUtils.cc [hunk 1]
```diff
@@ -440,7 +444,7 @@ static DH *
 get_dh2048()
```
Comment (jpeach) [inline iocore/net/SSLUtils.cc]: It would be nice to rename this to ``DH_get_2048_256`` and only define it for the backwards compatibility case.

**Comment by bryancall** [comment]
👍 - Looked pretty straight forward and didn't break working with OpenSSL 1.0.2.

**Comment by zwoop** [comment]
I can't get Jenkins to behave, but there are build errors from this on FreeBSD:

    SSLUtils.cc:445:1: error: static declaration of 'DH_get_2048_256' follows non-static declaration
    DH_get_2048_256()
    ^
    /usr/local/include/openssl/dh.h:241:5: note: previous declaration is here
    DH *DH_get_2048_256(void);
        ^

**Comment by shinrich** [comment]
Interesting.  It looks like the openssl version on freeBSD is not labeled 1.1, but it does have this particular function.  We could do configure time checks to determine whether the DH_get_2048_256 function is present in openssl, or we could revert my last commit, and have the original wrapper function which calls DH_get_2048_256 only if the openssl version is 1.1 or better.

**Comment by zwoop** [comment]
A check might be more portable going forward? Like, maybe this is a libressl or something issue ?

**Comment by jpeach** [comment]
> On May 16, 2016, at 7:13 AM, Susan Hinrichs <notifications@github.com> wrote:
> 
> Interesting. It looks like the openssl version on freeBSD is not labeled 1.1, but it does have this particular function. We could do configure time checks to determine whether the DH_get_2048_256 function is present in openssl, or we could revert my last commit,
> 

Yes this is the best approach. Teat for the API you need and emulate if it is not available. Relying on version numbers will be a game of whack-a-mole.

**Comment by zwoop** [comment]
I agree on the first part, but depending on the situation, not on the second part. The emulations have caused grief (major bugs) in the past. What can happen in the emulation is that it doesn't emulate as you'd expect (which is exactly what happened with the SSL options we tried to emulate). I much prefer just not using the missing functionality if that is possible.

**Comment by shinrich** [comment]
The original code does not use the DH_get_2038_256 function.  It effectively rolled it's own.  I don't think this is a huge concern, Setting your own DH key seems to be a dying approach.  Using the ephemeral DH seems to be more popular these days.  As long as we do something reasonably sensible, we should be ok.  I'll work on adding the configure time check.

**Comment by shinrich** [comment]
Added the automake check for DH_get_2048_256 and verified it on openssl 1.0.1 and openssl 1.1.

**Comment by zwoop** [comment]
This built and tested on Linux and FreeBSD.

https://ci.trafficserver.apache.org/view/github/job/Github-Linux/79/
https://ci.trafficserver.apache.org/view/github/job/Github-FreeBSD/174/
