### PR TITLE
Resolve OpenSSL 4.0 build issues

### LINKED ISSUE #13427: 10.2.x branch cannot build on Fedora 45 due to ASN1_STRING opacity
Fedora 45 migrates to OpenSSL 4.0.  In OpenSSL 4.0, the ASN1_STRING type is now opaque, and accessors must be used, see https://docs.openssl.org/4.0/man7/ossl-guide-migration/#the-asn1_string-type-is-now-opaque

`X509HostnameValidator.cc:do_check_string()` attempts to access opaque internals and thus will not compile with OpenSSL 4.0

### PR DESCRIPTION
**Pull request by jeredfloyd**
Fedora 45 updates to OpenSSL 4.0, which removes several long-deprecated capabilities and breaks ATS build.   Specific issues fixed are lack of const tagging of pointers to immutable structures, and disallowed introspection of ASN1_STRING. Resolves #13427

### CODE REVIEW

**Comment by JosiahWI** [comment]
[approve ci]

**Comment by JosiahWI** [comment]
@jeredfloyd Could you run the `clang-format` CMake target?

**Comment by jeredfloyd** [comment]
@JosiahWI oops; done

**Comment by JosiahWI** [comment]
> ../src/tscore/X509HostnameValidator.cc:269:15: error: no matching function for call to 'X509_NAME_get_index_by_NID'
  while ((i = X509_NAME_get_index_by_NID(name, NID_commonName, i)) >= 0) {
              ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/x509.h:810:5: note: candidate function not viable: 1st argument ('const X509_NAME *' (aka 'const X509_name_st *')) would lose const qualifier
int X509_NAME_get_index_by_NID(X509_NAME *name, int nid, int lastpos);

Apparently, not all the X509 APIs in older OpenSSL versions take the name as pointer to const. Would it work to use `auto` or `decltype` to determine the type of the local variable, so that it automatically assumes the correct type for both APIs? (If this approach is used, there should be a comment explaining why this was done.) That's just one idea; I'm interested in how you recommend to fix it.

**Comment by jeredfloyd** [comment]
Huh.  I can't access the trafficserver CI logs; can you tell me what OS versions / OpenSSL versions are in use on the failing CentOS/Debian/FreeBSD/Ubuntu jobs?

I don't see why `decltype` wouldn't work, but I don't work much with C++ so I don't want to proffer a strong opinion here.

**Comment by JosiahWI** [comment]
Ubuntu 20.04.6
FreeBSD 13.1

The Debian and CentOS failures were due to GitHub connectivity issues.

**Comment by bneradt** [comment]
freebsd and ubuntu both failed for const issues:

```
FAILED: src/tscore/CMakeFiles/tscore.dir/X509HostnameValidator.cc.o 
/usr/bin/ccache /usr/lib/llvm-12/bin/clang++ -DDEBUG -DPACKAGE_NAME="\"Apache Traffic Server\"" -DPACKAGE_VERSION=\"11.0.0\" -D_DEBUG -Dlinux -I/home/jenkins/workspace/Github_Builds/ubuntu/src/include -I/home/jenkins/workspace/Github_Builds/ubuntu/src/build/include -I/home/jenkins/workspace/Github_Builds/ubuntu/src/build/src/tscore -I/home/jenkins/workspace/Github_Builds/ubuntu/src/lib/swoc/include -I/home/jenkins/workspace/Github_Builds/ubuntu/src/lib/yamlcpp/include -isystem /home/jenkins/workspace/Github_Builds/ubuntu/src/lib/systemtap -D_FORTIFY_SOURCE=2 -fPIE -fstack-protector -pthread -g -std=c++20 -fPIC -Wthread-safety -Werror=thread-safety -Wno-invalid-offsetof -pipe -Wall -Wextra -Wno-noexcept-type -Wsuggest-override -Wno-vla-extension -fno-strict-aliasing -mcx16 -Werror -MD -MT src/tscore/CMakeFiles/tscore.dir/X509HostnameValidator.cc.o -MF src/tscore/CMakeFiles/tscore.dir/X509HostnameValidator.cc.o.d -o src/tscore/CMakeFiles/tscore.dir/X509HostnameValidator.cc.o -c /home/jenkins/workspace/Github_Builds/ubuntu/src/src/tscore/X509HostnameValidator.cc
../src/tscore/X509HostnameValidator.cc:269:15: error: no matching function for call to 'X509_NAME_get_index_by_NID'
  while ((i = X509_NAME_get_index_by_NID(name, NID_commonName, i)) >= 0) {
              ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/x509.h:810:5: note: candidate function not viable: 1st argument ('const X509_NAME *' (aka 'const X509_name_st *')) would lose const qualifier
int X509_NAME_get_index_by_NID(X509_NAME *name, int nid, int lastpos);
    ^
1 error generated.
```

**Comment by jeredfloyd** [comment]
Thanks; sorry -- I'll see if I can make time for this tomorrow.

**Comment by maskit** [comment]
We deal with a similar const-ness difference at another place. `const_cast` is acceptable.
https://github.com/apache/trafficserver/blob/3df2bceb04b4c022aaf5bef67d9986c90fa81fbe/src/iocore/net/OCSPStapling.cc#L370-L371


FYI:

`X509_NAME_get_index_by_NID`:

| Version                        | Signature                                                                      |
| ------------------------------ | ------------------------------------------------------------------------------ |
| OpenSSL 1.1.1                  | `int X509_NAME_get_index_by_NID(X509_NAME *name, int nid, int lastpos);`       |
| OpenSSL 3.0                    | `int X509_NAME_get_index_by_NID(const X509_NAME *name, int nid, int lastpos);` |
| OpenSSL master (post-constify) | `int X509_NAME_get_index_by_NID(const X509_NAME *name, int nid, int lastpos);` |
| BoringSSL (current)            | `int X509_NAME_get_index_by_NID(const X509_NAME *name, int nid, int lastpos);` |

`X509_get_subject_name`:

| Version                        | Signature                                                |
| ------------------------------ | -------------------------------------------------------- |
| OpenSSL 1.1.1                  | `X509_NAME *X509_get_subject_name(const X509 *a);`       |
| OpenSSL 3.0                    | `X509_NAME *X509_get_subject_name(const X509 *a);`       |
| OpenSSL master (post-constify) | `const X509_NAME *X509_get_subject_name(const X509 *a);` |
| BoringSSL                      | `X509_NAME *X509_get_subject_name(const X509 *x509);`    |

**Comment by bneradt** [comment]
> Thanks; sorry -- I'll see if I can make time for this tomorrow.

Thank you for working on this!

**Comment by jeredfloyd** [comment]
Closing in favor of expanded #13476
