### ISSUE TITLE
ubuntu build is broken(inc CI).

### ISSUE THREAD

**Issue by brbzull0** [apache/trafficserver#11068]
It seems it's broken after https://github.com/apache/trafficserver/pull/11066 got into master.

https://ci.trafficserver.apache.org/job/master/job/os_build/26915/console

my local ubuntu 20.04:
```
FAILED: plugins/cache_promote/CMakeFiles/cache_promote.dir/configs.cc.o 
/usr/bin/c++ -DDEBUG -DPACKAGE_NAME=\"ats\" -DPACKAGE_VERSION=\"10.0.0\" -D_DEBUG -Dcache_promote_EXPORTS -Dlinux -I../include -Iinclude -I../lib/swoc/include -I../lib/yamlcpp/include -isystem /opt/ats_bssl/boringssl/include -O0 -g -Wall -Wextra -Wno-unused-parameter -Wnon-virtual-dtor -pthread -g -fPIC -Wno-invalid-offsetof -pipe -Wall -Wextra -Wno-unused-parameter -Wno-noexcept-type -Wsuggest-override -Wno-format-truncation -Wno-stringop-overflow -std=c++2a -MD -MT plugins/cache_promote/CMakeFiles/cache_promote.dir/configs.cc.o -MF plugins/cache_promote/CMakeFiles/cache_promote.dir/configs.cc.o.d -o plugins/cache_promote/CMakeFiles/cache_promote.dir/configs.cc.o -c ../plugins/cache_promote/configs.cc
In file included from /opt/ats_bssl/boringssl/include/openssl/base.h:61,
                 from /opt/ats_bssl/boringssl/include/openssl/sha.h:60,
                 from ../plugins/cache_promote/lru_policy.h:22,
                 from ../plugins/cache_promote/configs.cc:21:
/usr/include/c++/9/stdlib.h:65:12: error: ‘void* malloc(size_t)’ conflicts with a previous declaration
   65 | using std::malloc;
      |            ^~~~~~
In file included from ../plugins/cache_promote/policy.h:23,
                 from ../plugins/cache_promote/configs.h:20,
                 from ../plugins/cache_promote/configs.cc:20:
../include/ts/ts.h:3088:1: note: previous declaration ‘template<class T> T* malloc(size_t)’
 3088 | malloc(size_t count = 1)
      | ^~~~~~
[370/1078] Building CXX object src/iocore/cache/CMakeFiles/Update_S_to_L.dir/unit_tests/main.cc.o
```
