### PR TITLE
Fix macOS build

### PR DESCRIPTION
**Pull request by masaori335**
`F_GETPIPE_SZ` is introduced by #5863, but it's not available on mac neither. 

```
  CXX      LogFilter.o
../../../proxy/logging/LogFile.cc:196:42: error: use of undeclared identifier 'F_GETPIPE_SZ'
      long pipe_size = (long)fcntl(m_fd, F_GETPIPE_SZ);
                                         ^
../../../proxy/logging/LogFile.cc:203:29: error: use of undeclared identifier 'F_SETPIPE_SZ'
      int ret = fcntl(m_fd, F_SETPIPE_SZ, m_pipe_buffer_size);
                            ^
../../../proxy/logging/LogFile.cc:208:37: error: use of undeclared identifier 'F_GETPIPE_SZ'
      pipe_size = (long)fcntl(m_fd, F_GETPIPE_SZ);
                                    ^
  CXX      LogFormat.o
3 errors generated.
make[2]: *** [LogFile.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```
https://ci.trafficserver.apache.org/view/10.x%20master/job/macOS-master/compiler=clang,label=macOS,type=release/2574/console

/cc @ericcarlschwartz

### CODE REVIEW

File: proxy/logging/LogFile.cc [hunk 1]
```diff
@@ -188,9 +188,7 @@ LogFile::open_file()
       return LOG_FILE_NO_PIPE_READERS;
     }
 
-#ifdef __FreeBSD__
-    // we don't do this for FreeBSD
-#else
+#ifdef __linux__
```
Comment (maskit) [inline proxy/logging/LogFile.cc]: Why not F_GETPIPE_SZ?

Comment (maskit) [reply proxy/logging/LogFile.cc]: In either way, the doc should be fixed too.

Comment (masaori335) [reply proxy/logging/LogFile.cc]: Should be. I was pulled by `__FreeBDS__`.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.
